### PR TITLE
Propose an all new name

### PR DESCRIPTION
**Pull request by devesh-shetty**
@ryanbalsdon

### CODE REVIEW

**Comment by ryanbalsdon** [comment]
It's a serialization library in C. serial/cerial? That's a bit too subtle?

**Review by abhiin1947 — CHANGES_REQUESTED** [review]
:pleasedontproceed:

**Comment by devesh-shetty** [comment]
> It's a serialization library in C. serial/cerial? That's a bit too subtle?

CReel, SeeReel

**Comment by ryanbalsdon** [comment]
> Pull requests can be made in participating GitHub-hosted repositories/projects, classified with the Hacktoberfest topic.

**Comment by ryanbalsdon** [comment]
There's still time to get yourself a tshirt! Just need to find one of those participating repos.

**Pull request closed without merging**
